services:
    jupyter:
        build: .
        container_name: lab1-PTIA
        ports:
            - "8888:8888"
        volumes:
            - ./notebooks:/home/jovyan/work
        #environment:
        #    - JUPYTER_TOKEN=my-secret-token
